global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'go-hm2-app'
    static_configs:
      - targets: ['app:8080']
        labels:
          service: 'go-hm2'
    metrics_path: '/metrics'
    scrape_interval: 5s

